import Vue from "vue";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon, FontAwesomeLayers } from "@fortawesome/vue-fontawesome";
import {
    faPlus,
    faCog,
    faTrashAlt,
    faChevronLeft,
    faChevronRight,
    faTools,
    faBars,
    faTimes,
    faFileImage,
    faGlobeAmericas,
    faGripVertical,
    faPencilRuler,
    faArrowsAltV,
    faHeading,
    faColumns,
    faParagraph,
    faGripHorizontal,
    faBold,
    faListUl,
    faRedo,
    faUndo,
    faItalic,
    faListOl,
    faStrikethrough,
    faUnderline,
    faToggleOn,
    faToggleOff,
    faAlignLeft,
    faAlignRight,
    faAlignCenter,
    faAlignJustify,
    faSave,
    faFolderOpen,
    faCloud,
    faLock,
    faUnlock,
    faChevronDown,
    faHeart,
    faStickyNote,
    faTable,
    faMinus,
    faEdit,
    faCheck,
    faArrowUp,
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faPaw,
    faFile,
    faExclamationCircle
  } from "@fortawesome/free-solid-svg-icons";
  import { faHeart as farHeart } from "@fortawesome/free-regular-svg-icons";

  library.add(faPlus);
  library.add(faCog);
  library.add(faTrashAlt);
  library.add(faChevronLeft);
  library.add(faChevronRight);
  library.add(faChevronDown);
  library.add(faTools);
  library.add(faBars);
  library.add(faTimes);
  library.add(faFileImage);
  library.add(faGlobeAmericas);
  library.add(faArrowsAltV);
  library.add(faGripVertical);
  library.add(faPencilRuler);
  library.add(faHeading);
  library.add(faColumns);
  library.add(faParagraph);
  library.add(faGripHorizontal);
  library.add(faBold);
  library.add(faListUl);
  library.add(faRedo);
  library.add(faUndo);
  library.add(faItalic);
  library.add(faListOl);
  library.add(faStrikethrough);
  library.add(faUnderline);
  library.add(faToggleOn);
  library.add(faToggleOff);
  library.add(faAlignLeft);
  library.add(faAlignRight);
  library.add(faAlignCenter);
  library.add(faAlignJustify);
  library.add(faSave);
  library.add(faFolderOpen);
  library.add(faCloud);
  library.add(faLock);
  library.add(faUnlock);
  library.add(faHeart);
  library.add(farHeart);
  library.add(faStickyNote);
  library.add(faTable);
  library.add(faMinus);
  library.add(faEdit);
  library.add(faCheck);
  library.add(faArrowUp);
  library.add(faArrowDown);
  library.add(faArrowLeft);
  library.add(faArrowRight);
  library.add(faPaw);
  library.add(faFile);
  library.add(faExclamationCircle);

  Vue.component("font-awesome-icon", FontAwesomeIcon);
  Vue.component("font-awesome-layers", FontAwesomeLayers);